## 1. Read Me 
**Run first cell :** install dependencies 

**Run second cell :** install files and local environment on the VM, choose which task you want to run by setting task_1 or task_2 value to true

**Run third cell :** try diferent init of the agent. When one is found -> the agent is trained  

In [1]:
# Dependencies

!pip install torch numpy git+https://github.com/cs4246/gym-grid-driving.git
!pip install -U -q PyDrive

  Cloning https://github.com/cs4246/gym-grid-driving.git to /tmp/pip-req-build-fctwn1g0
  Running command git clone -q https://github.com/cs4246/gym-grid-driving.git /tmp/pip-req-build-fctwn1g0
  Created wheel for gym-grid-driving: filename=gym_grid_driving-0.0.1-cp36-none-any.whl size=8623 sha256=bc4454ea0e35965f441cd1b5bdb614dc8c5f26a6e5a49c1f2fed354bae15059d
  Stored in directory: /tmp/pip-ephem-wheel-cache-wmcuu9ja/wheels/e1/30/f2/157c0938ab9bfe9c10c29c9fcab8392f587c9d141f215b67ca
Successfully built gym-grid-driving


In [0]:
!git clone https://github.com/pytorch/examples.git

Cloning into 'examples'...
remote: Enumerating objects: 2333, done.
remote: Total 2333 (delta 0), reused 0 (delta 0), pack-reused 2333
Receiving objects: 100% (2333/2333), 39.02 MiB | 19.27 MiB/s, done.
Resolving deltas: 100% (1172/1172), done.


In [2]:
# Authentification / Initialization of workspace 

import os
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

# Create repo folders 

task_1 = False
# If False task_2 workplace will be downloaded

if task_1:
  number_task = 1
else:
  number_task = 2

root = '/content'
local_download = os.path.join(root,'HW3_Task{}'.format(number_task))

if not(os.path.exists(local_download)): 
  os.mkdir(local_download)

local_download_agent = os.path.join(local_download,'agent')

if not(os.path.exists(local_download_agent)): 
  os.mkdir(local_download_agent)

  # Download files 


def download_list(file_list,path_name):
    
  error_l = [];
    
  for f in file_list:
    # 3. Create & download by id.
  
    print('file found : title: %s, id: %s' % (f['title'], f['id']))
    try:
      #print('title: %s, id: %s' % (f['title'], f['id']))
      fname = os.path.join(path_name, f['title'])
      
      # Download only .py files
      if fname[-3:] == ".py":
        print('downloading to {}'.format(fname))
        f_ = drive.CreateFile({'id': f['id']})
        f_.GetContentFile(fname)
      
    except:
      print("there is an error")          
      error_l.append(fname)


if task_1:
  # Initial folder
  local_download_path = local_download_agent

  # Agent files 
  file_list = drive.ListFile(
        {'q': "'1ktZR8KIIWEi8Cre92SFomSEchWleHtSu' in parents"}).GetList()

  download_list(file_list,local_download_path)


  # Initial files
  local_download_path = local_download

  file_list = drive.ListFile(
        {'q': "'1x4sJIKHA6NZ5y78AnOJeCZP8abI4gLLO' in parents"}).GetList()

  download_list(file_list,local_download_path)

else:

  # Initial folder
  local_download_path = local_download_agent

  # Agent files 
  file_list = drive.ListFile(
        {'q': "'1PUrHkG6ki4JsiXtKOtvc2vAuR6IJMnCa' in parents"}).GetList()

  download_list(file_list,local_download_path)


  # Initial files
  local_download_path = local_download

  file_list = drive.ListFile(
        {'q': "'17wsroYnRmoTt-OIzDJRrUNvVFmohBVFR' in parents"}).GetList()

  download_list(file_list,local_download_path)



file found : title: __init__.py, id: 1WO1O3RwqCpk7XdN07UUZbF6YTaj5mGGg
downloading to /content/HW3_Task2/agent/__init__.py
file found : title: models.py, id: 1BW6dbcbWvmC7JbqE78269K1IXIPwtlEi
downloading to /content/HW3_Task2/agent/models.py
file found : title: model.pt, id: 1_hr_fysoSC6AXix1Qjqq0bBYk0KiSIcq
file found : title: .ipynb_checkpoints, id: 14rimDklDDBO4_OqcqfbiybhzNMxQQFSm
file found : title: env.py, id: 1bYr6NdzVOXe77n-gUac3VdGA8tnpS8HJ
downloading to /content/HW3_Task2/agent/env.py
file found : title: ZZZ.zip, id: 1CVWs9pxeQ6FieIRMszIIfNK1my32N3Wl
file found : title: ZZZ, id: 10kHEkPFSjAINnDqi2s5KF7PxQN9bImk3
file found : title: try2 2, id: 1Ka1yYoo2aGsxPITkqKfBYB4AAHln0aMZ
file found : title: try2.zip, id: 1o5hCQ_s6UkmcbRNTkR8crcNcftp1IhZ7
file found : title: try2 2.zip, id: 1R8lmVqVxgvfuQ150WK4ZckNmfjvWmvW4
file found : title: try2, id: 1T1A0dN0enM4yy8DmA6A7HJOFyGQS0IlX
file found : title: A0212190W_Task2.zip, id: 1XJ9tRmPvxju3IjD76WkmINyUlYTIJvVm
file found : title: ag

In [9]:
!python HW3_Task2/agent/q_learning.py 

[[[0. 0. 0. ... 1. 0. 0.]
  [0. 0. 0. ... 0. 1. 0.]
  [1. 0. 0. ... 1. 1. 0.]
  ...
  [1. 0. 1. ... 0. 1. 0.]
  [0. 0. 0. ... 1. 0. 1.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[1. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]
Traceback (most recent call last):
  File "HW3_Task2/agent/q_learning.py", line 78, in <module>
    action = np.argmax(q_table[state])
IndexError: arrays used as indices must be of integer (or boolean) type


In [0]:
# TASK 2

import time
duree = 0 
nb_bad_init = 0 
# Try for 10 diferent inits

for i in range(0,1):
  debut = time.time()
  # Try an init 
  !python3 HW3_Task2/agent/models.py --train
  #!python3 HW3_Task2/agent/testenv.py
  duree = (time.time()-debut)
  # If good init exit loop
  print(duree)
  if duree > 10000:
    break


ConvDQN(
  (features): Sequential(
    (0): Conv2d(4, 32, kernel_size=(2, 2), stride=(1, 1))
    (1): ReLU()
    (2): Conv2d(32, 64, kernel_size=(2, 2), stride=(1, 1))
    (3): ReLU()
  )
  (layers): Sequential(
    (0): Linear(in_features=24576, out_features=256, bias=True)
    (1): ReLU()
    (2): Linear(in_features=256, out_features=5, bias=True)
  )
)
/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py:3335: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/usr/local/lib/python3.6/dist-packages/numpy/core/_methods.py:161: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
[Episode 10]	avg rewards : 0.000,	avg loss: : nan,	buffer size : 52,	epsilon : 98.0%
[Episode 20]	avg rewards : 0.000,	avg loss: : nan,	buffer size : 99,	epsilon : 96.1%
[Episode 30]	avg rewards : 0.000,	avg loss: : nan,	buffer size : 138,	epsilon : 94.2%
[Episode 40]	avg rewards : 0.000,	avg loss: : nan,	buffer size : 178,	epsilon : 92.4%
[Episod

In [0]:
# Test for TASK 2:
!python3 HW3_Task2/agent/__init__.py


[task_2_tmax50] 300 run(s) avg rewards : 0.0
[task_2_tmax40] 300 run(s) avg rewards : 0.0
Point: 0.0
Local runtime: 291.5432770252228 seconds --- safe


In [0]:
# TASK 1

import time
duree = 0 
nb_bad_init = 0 
# Try for 10 diferent inits

for i in range(0,10):
  debut = time.time()
  # Try an init 
  !python3 HW3_Task1/agent/dqn.py --train
  duree = (time.time()-debut)
  # If good init exit loop
  if duree > 100:
    break

python3: can't open file 'HW3_Task1/agent/dqn.py': [Errno 2] No such file or directory


KeyboardInterrupt: ignored